#!/bin/sh

# post-checkout hook - looks for package changes or migrations every time you change branches

echo "Starting post-checkout hook"

# Exit early if this was only a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

oldRef=$1
newRef=$2

function changed {
  git diff --name-only $oldRef $newRef | grep "^$1" > /dev/null 2>&1
}

if changed 'src/webapp/server/migrations'; then
  echo "Migrations pending, migrating"
  (cd src; docker-compose run webapp /webapp/server/node_modules/.bin/sequelize db:migrate)
fi

if changed 'src/webapp/client/bower.json'; then
  echo "Install webapp client bower packages"
  (cd src/webapp/client; bower install; bower prune)
fi

if changed 'src/webapp/client/package.json'; then
  echo "Install webapp client npm packages"
  (cd src/webapp/client; npm install; npm prune)
fi

if changed 'src/webapp/server/package.json'; then
  echo "Install webapp server npm packages"
  echo "$(pwd)"
  (cd src/webapp/server; echo pwd; npm install; npm prune)
fi

echo "Done with post-checkout hook"
