#!/bin/sh

# post-merge hook - looks for package changes or migrations every time you `git merge` or `git pull`

echo "Starting post-merge hook"

PATH=$PATH:/usr/local/bin:/usr/local/sbin # http://stackoverflow.com/questions/12881975/git-pre-commit-hook-failing-in-github-for-mac-works-on-command-line

function changed {
  git diff --name-only | grep "^$1" > /dev/null 2>&1
}

if changed 'src/webapp/server/migrations'; then
  echo "Migrations pending, migrating"
  (cd src; docker-compose run webapp /webapp/server/node_modules/.bin/sequelize db:migrate)
fi

if changed 'src/webapp/client/bower.json'; then
  echo "Installing webapp client bower packages"
  (cd src/webapp/client; bower install; bower prune)
fi

if changed 'src/webapp/client/package.json'; then
  echo "Installing webapp client npm packages"
  (cd src/webapp/client; npm install; npm prune)
fi

if changed 'src/webapp/server/package.json'; then
  echo "Installing webapp server npm packages"
  (cd src/webapp/server; npm install; npm prune)
fi

echo "Done with post-merge hook"
