version: 2
jobs:
  build:
    parallelism: 3

    environment:
      METEOR_ALLOW_SUPERUSER: 1
      LANG: C
      LC_ALL: C.UTF-8
    
    docker:
      - image: abernix/meteord:node-12.16.1-base
      - image: circleci/mongo:4.0.6
        command: --port 3001

    steps:
      - checkout

      - run: 
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - run:
          name: Update PATH for Yarn
          command: |
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run: 
          name: Install Meteor
          command: |
            if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
            if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

      - run:
          name: Install Selenium dependencies
          command: |
            apt-get update
            apt-get install openjdk-8-jdk-headless -y

      - run:
          name: Install Chrome
          command: |
            apt-get install lsb-release=4.1+Debian13+nmu1 libappindicator3-1=0.4.92-3.1 fonts-liberation=1.07.4-1 -y
            apt-get install libxss1=1:1.2.2-1 wget xdg-utils libgbm1 -y
            CHROME_VERSION=79.0.3945.130-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
            dpkg -i google-chrome.deb
            sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox --headless|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run: 
          name: Print Environment
          command: |
            echo "environment versions:"
            . /etc/os-release
            echo "operating system $VERSION"
            echo "kernel $(uname -a)"
            echo "which java: $(which java)"
            echo "java $(java -version)"
            echo "which node: $(which node)"
            echo "node $(node -v)"
            echo "METEOR_WATCH_FORCE_POLLING: $METEOR_WATCH_FORCE_POLLING"
            echo "$(meteor --version)"
            echo "meteor node $(meteor node -v)"
            echo "yarn $(yarn -v)"

      - restore_cache:
          name: Restore Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "circle.yml" }}

      - run:
          name: Install Yarn packages
          command: |
            yarn install --frozen-lockfile
            yarn list

      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/.cache/yarn
            - ~/project/node_modules
            - /opt/circleci/nodejs/v12.16.1/lib/node_modules

      - restore_cache:
          name: Restore Meteor release cache
          key: meteor-release-{{ checksum ".meteor/release" }}-{{ checksum "circle.yml" }}

      - restore_cache:
          name: Restore Meteor packages cache
          key: meteor-packages-{{ checksum ".meteor/versions" }}-{{ checksum "circle.yml" }}

      - run:
          name: Build Meteor app & dependencies
          command: ./.testing/cache_build_and_dependencies.sh
          no_output_timeout: 1200s

      - save_cache:
          name: Save Meteor release cache
          key: meteor-release-{{ checksum ".meteor/release" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/.meteor/packages
            - ~/.meteor/package-metadata

      - save_cache:
          name: Save Meteor packages cache
          key: meteor-packages-{{ checksum ".meteor/versions" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/project/.meteor/local/build
            - ~/project/.meteor/local/bundler-cache
            - ~/project/.meteor/local/isopacks # need to figure out when this expires
            - ~/project/.meteor/local/plugin-cache

      - run: case $CIRCLE_NODE_INDEX in 0) (meteor npm run test) ;; 1) (meteor npm run test-app) ;; 2) (./tests/acceptance_run) ;; esac
    
      - store_artifacts:
          path: node_cache/_logs
      - store_artifacts:
          path: .meteor/local/log
      - store_artifacts:
          path: ~/.config/yarn/global/yarn-error.log


  deploy:
    environment:
      METEOR_ALLOW_SUPERUSER: 1

    docker:
      - image: abernix/meteord:node-12.16.1-base
      
    steps:
      - checkout

      - run: 
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - run:
          name: Update PATH for Yarn
          command: |
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run: 
          name: Install Yarn packages
          command: |
            yarn install --frozen-lockfile --production
            yarn list
      
      - run: 
          name: Install Meteor
          command: |
            if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
            if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

      - run: (cd ~/project/.deploy/production; gpg --no-use-agent --quiet --passphrase $MUP_PASSPHRASE -o mup.js -d mup.js.gpg)
      - run: yarn global add ssh2@0.4.15 # needed for meteor-up
      - run: yarn global add mup@1.4.6
      - run: (cd ~/project/.deploy/production; DEBUG=mup* mup deploy --verbose)
      - run: curl https://api.rollbar.com/api/1/deploy/ -F access_token=$ROLLBAR_SERVER_ACCESS_TOKEN -F environment=production -F revision=$CIRCLE_SHA1 -F local_username=$CIRCLE_USERNAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master