#!/bin/sh

if [ "${PWD##*/}" != "scripts" ]
then
  echo "Please make sure your current working directory is the scripts folder!"
  exit
fi


echo "Installing PhantomJS..."
brew update
brew install phantomjs198

echo "Installing bower..."
npm install -g bower@1.7.0

echo "Installing webapp bower packages..."
(cd ../src/webapp; bower install; bower prune)

echo "Installing webapp npm packages..."
(cd ../src/webapp; npm install; npm prune)

echo "Done installing development packages"
