#!/bin/sh

# post-merge hook - looks for package changes or migrations every time you `git merge` or `git pull`

echo "Starting post-merge hook"

PATH=$PATH:/usr/local/bin:/usr/local/sbin # http://stackoverflow.com/questions/12881975/git-pre-commit-hook-failing-in-github-for-mac-works-on-command-line

function changed {
  git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'src/webapp/migrations'; then
  echo "Migrations pending, migrating"
  (cd src; docker-compose run webapp grunt db:migrate)
fi

if changed 'src/webapp/assets/bower.json'; then
  echo "Installing webapp bower packages"
  (cd src/webapp/assets; bower install; bower prune)
fi

if changed 'src/webapp/package.json'; then
  echo "Installing webapp npm packages"
  (cd src/webapp; npm install; npm prune)
fi

echo "Done with post-merge hook"
