#!/bin/sh

# post-checkout hook - looks for package changes or migrations every time you change branches

echo "Starting post-checkout hook"

# Exit early if this was only a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

PATH=$PATH:/usr/local/bin:/usr/local/sbin # http://stackoverflow.com/questions/12881975/git-pre-commit-hook-failing-in-github-for-mac-works-on-command-line

oldRef=$1
newRef=$2

function changed {
  git diff --name-only $oldRef $newRef | grep "^$1" > /dev/null 2>&1
}

if changed 'src/webapp/migrations'; then
  echo "Migrations pending, migrating"
  (cd src; docker-compose run webapp grunt db:migrate)
fi

if changed 'src/webapp/assets/bower.json'; then
  echo "Installing webapp bower packages"
  (cd src/webapp/assets; bower install; bower prune)
fi

if changed 'src/webapp/package.json'; then
  echo "Installing webapp npm packages"
  (cd src/webapp; npm install; npm prune)
fi

echo "Done with post-checkout hook"
